[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
bevy_quinnet = { version = "0.17.0", default-features = false, features = ["client", "shared-client-id"] }
shared = { path = "../shared" }
