[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = { version = "0.15.3", features = ["wayland", "dynamic_linking"] }
bevy_rapier3d = { version = "0.29.0", features = ["debug-render-3d", "enhanced-determinism", "serde-serialize"] }
shared = { path = "../shared" }