[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy.workspace = true
bevy_rapier3d.workspace = true
bevy_renet.workspace = true
serde.workspace = true
bincode.workspace = true
